import * as Defaults from './constants';

export interface AIConfig {
  BASE_REWARD: number;
  HORIZON: number;
  SAVINGS_THRESHOLD_RATIO: number;
  DANGER_PENALTY_RATIO: number;
  KNIGHT_HARASSMENT_BONUS: number;
  LETHAL_THREAT_PENALTY_MULT: number;
  IMMEDIATE_CAPTURE_BONUS: number;
  EXPANSION_DISTANCE_BONUS: number;
  PLAINS_PRIORITY_BONUS: number;
  UNCLAIMED_VILLAGE_PRIORITY_BONUS: number;
  PUT_ENEMY_IN_PERIL_BONUS: number;
  UPGRADE_GOLD_MINE_BONUS: number;
  UPGRADE_VILLAGE_BONUS: number;
  KNIGHT_SNIPE_BONUS: number;
  CATAPULT_SIEGE_BONUS: number;
  KILL_PRIORITY_BONUS: number;
  DRIVE_OUT_BONUS: number;
  SKIRMISH_BIAS: number;
  SIEGE_OVERRIDE_BONUS: number;
  GOLD_RESERVE_TARGET: number;
  LETHALITY_WEIGHT_BONUS: number;
  DEFENSE_URGENCY_BONUS: number;
  UNIT_TO_SETTLEMENT_RATIO: number;
}

export const DEFAULT_AI_CONFIG: AIConfig = {
  BASE_REWARD: Defaults.BASE_REWARD,
  HORIZON: Defaults.HORIZON,
  SAVINGS_THRESHOLD_RATIO: Defaults.SAVINGS_THRESHOLD_RATIO,
  DANGER_PENALTY_RATIO: Defaults.DANGER_PENALTY_RATIO,
  KNIGHT_HARASSMENT_BONUS: Defaults.KNIGHT_HARASSMENT_BONUS,
  LETHAL_THREAT_PENALTY_MULT: Defaults.LETHAL_THREAT_PENALTY_MULT,
  IMMEDIATE_CAPTURE_BONUS: Defaults.IMMEDIATE_CAPTURE_BONUS,
  EXPANSION_DISTANCE_BONUS: Defaults.EXPANSION_DISTANCE_BONUS,
  PLAINS_PRIORITY_BONUS: Defaults.PLAINS_PRIORITY_BONUS,
  UNCLAIMED_VILLAGE_PRIORITY_BONUS: Defaults.UNCLAIMED_VILLAGE_PRIORITY_BONUS,
  PUT_ENEMY_IN_PERIL_BONUS: Defaults.PUT_ENEMY_IN_PERIL_BONUS,
  UPGRADE_GOLD_MINE_BONUS: Defaults.UPGRADE_GOLD_MINE_BONUS,
  UPGRADE_VILLAGE_BONUS: Defaults.UPGRADE_VILLAGE_BONUS,
  KNIGHT_SNIPE_BONUS: Defaults.KNIGHT_SNIPE_BONUS,
  CATAPULT_SIEGE_BONUS: Defaults.CATAPULT_SIEGE_BONUS,
  KILL_PRIORITY_BONUS: Defaults.KILL_PRIORITY_BONUS,
  DRIVE_OUT_BONUS: Defaults.DRIVE_OUT_BONUS,
  SKIRMISH_BIAS: 15.0,
  SIEGE_OVERRIDE_BONUS: 40.0,
  GOLD_RESERVE_TARGET: 100.0,
  LETHALITY_WEIGHT_BONUS: 30.0,
  DEFENSE_URGENCY_BONUS: 4.0,
  UNIT_TO_SETTLEMENT_RATIO: Defaults.UNIT_TO_SETTLEMENT_RATIO,
};
