export const BASE_REWARD = 500;

// Economic & General
export const HORIZON = 10;
export const BARBARIAN_EXPANSION_BUDGET_RATIO = 1/3;
export const SAVINGS_THRESHOLD_RATIO = 0.2; // Spend more gold on income-generating buildings
export const CHEAP_UNIT_THRESHOLD = 50;
export const MAX_TURNS_TO_ACT = 8;
export const DEFENSE_DISTANCE_THRESHOLD = 3;
export const NEAR_BASE_BONUS = 3.0;
export const INFLUENCE_BONUS_RATIO = 0.2;
export const COMPOSITION_RATIO_THRESHOLD = 0.5;
export const COMPOSITION_PENALTY_FACTOR = 1.0;
export const EMINENT_PERIL_BONUS = 10.0;
export const SACRIFICIAL_DEFENSE_BONUS = 5.0;
export const EMINENT_PERIL_PENALTY_RATIO = 0.5;
export const DANGER_PENALTY_RATIO = 5.0;
export const MIN_RECRUIT_THRESHOLD_THREAT = -50;
export const MIN_RECRUIT_THRESHOLD_NORMAL = 10;
export const INTERIOR_DISTANCE_THRESHOLD = 6;
export const INTERIOR_PENALTY_FACTOR = 15;
export const HEAT_MAP_RECRUIT_BONUS = 2.0;
export const HEAT_MAP_SAVINGS_THRESHOLD = 10;

// Unit Specific - Recruitment
export const KNIGHT_SNIPE_BONUS = 3.0;
export const KNIGHT_EXPANSION_BONUS = 4.0;
export const KNIGHT_INCOME_THRESHOLD = 25;
export const KNIGHT_INCOME_PENALTY = 1.0;
export const KNIGHT_APPEAL_BOOST = 1.5;
export const CATAPULT_SIEGE_BONUS = 4.0;
export const CATAPULT_CASTLE_BONUS = 2.0;
export const CATAPULT_DEFENSE_BONUS = 3.0;
export const CATAPULT_INCOME_THRESHOLD = 30;
export const CATAPULT_INCOME_PENALTY = 1.5;
export const CATAPULT_MOBILITY_PENALTY_FAR = 8.0;
export const CATAPULT_MOBILITY_PENALTY_VERY_FAR = 15.0;
export const CATAPULT_APPEAL_BOOST = 1.0;
export const CATAPULT_PROXIMITY_BONUS_L1 = 8.0;
export const CATAPULT_PROXIMITY_BONUS_L2 = 3.0;
export const CATAPULT_MEAT_SHIELD_RECRUIT_PENALTY = 10.0;
export const CATAPULT_MEAT_SHIELD_RECRUIT_BONUS = 2.0;
export const NEUTRAL_CAPTURE_BONUS = 0.5;

// Unit Actions
export const STAY_PUT_BIAS = 0.1;
export const IMMEDIATE_CAPTURE_BONUS = 20.0;
export const PILLAGE_SCORE_BONUS = 5.0; 
export const UNCLAIMED_VILLAGE_PRIORITY_BONUS = 60.0; 
export const PUT_ENEMY_IN_PERIL_BONUS = 28.0; 
export const EXPANSION_DISTANCE_BONUS = 7.5; 
export const PLAINS_PRIORITY_BONUS = 2.0; 
export const EDGE_OF_PERIL_BONUS = 15.0;
export const INFILLING_BONUS = 10.0;
export const PATHING_CONSISTENCY_BONUS = 0.2;
export const KNIGHT_HARASSMENT_BONUS = 5.0;
export const KNIGHT_SAFETY_BONUS = 8.0;
export const KNIGHT_FRIENDLY_SETTLEMENT_BONUS = 2.0;
export const CATAPULT_SAFETY_PENALTY_HIGH = 12.0;
export const CATAPULT_SIEGE_POSITION_BONUS = 3.0;
export const CATAPULT_SIEGE_PROXIMITY_BONUS = 1.5;
export const CATAPULT_DEFENSIVE_STAY_PUT_BONUS = 2.0;
export const DEFENSE_SCORING_BONUS = 3.5;
export const SACRIFICE_BONUS = 10.0;
export const COORDINATION_BONUS = 1.2;
export const INFLUENCE_PENALTY_HIGH_RATIO = 15.0;
export const INFLUENCE_PENALTY_MED_RATIO = 8.0;
export const INFLUENCE_EXPANSION_BONUS = 3.5; // Increased to value kingdom size
export const HVT_PROXIMITY_BONUS_FACTOR = 1.5;
export const SCREENING_BONUS = 5.0; // Increased to prioritize protecting HVTs
export const FORMATION_ANCHOR_BONUS = 8.0; // Units gain bonus for staying near a Catapult
export const SQUAD_INTEGRITY_BONUS = 3.0; // Units gain bonus for staying in a cluster (Distance 1-2)
export const ARCHER_PLACEMENT_BONUS = 15.0; // Bonus for distance 2 from enemy
export const CATAPULT_PLACEMENT_BONUS = 20.0; // Bonus for distance 3 from enemy
export const INFANTRY_FRONT_LINE_BONUS = 10.0; // Bonus for distance 1 from enemy
export const KNIGHT_FLANK_BONUS = 12.0;

export const MIN_SETTLEMENT_GROWTH_RATIO = 0.15;
export const COUNTER_ATTACK_BONUS = 9.0;
export const FOCUS_FIRE_BONUS = 4.0;
export const PREEMPTIVE_DEFENSE_BONUS = 8.0;
export const DRIVE_OUT_BONUS = 15.0;
export const LETHAL_THREAT_PENALTY_MULT = 5.0; // Doubled via GA to prioritize unit preservation
export const MUTUAL_SUPPORT_BONUS = 0.8;
export const KILL_PRIORITY_BONUS = 8.0;
export const THREAT_PENALTY_SACRIFICE_MULT = 0.2;
export const THREAT_PENALTY_L1_MULT = 15.0;
export const OPPORTUNISTIC_RETREAT_SETTLEMENT_BONUS = 15.0;
export const OPPORTUNISTIC_RETREAT_PLAINS_BONUS = 8.0;

// Advanced Tactics
export const SUPPORT_SCORE_MULT = 50;
export const RALLY_POINT_ADJACENCY_BONUS = 10;
export const BAIT_AND_TRADE_THRESHOLD = 150;
export const INFANTRY_VANGUARD_SETTLEMENT_BONUS = 5.0;
export const KNIGHT_FIRST_IN_PENALTY = 3.0;
export const CATAPULT_MEAT_SHIELD_BONUS = 10.0;
export const SETTLEMENT_DEGRADATION_PRIORITY_BONUS = 4.0;
export const COMBO_FOLLOW_UP_CLAIMER_BONUS = 12.0;
export const COMBO_FOLLOW_UP_NEUTRALIZER_BONUS = 8.0;
export const COMBO_SEQUENCING_STAY_PUT_PENALTY = 0.5;

export const UPGRADE_SAVING_MINE_BONUS = 40;
export const UPGRADE_SAVING_MINE_STAY_PUT_BONUS = 5;
export const UPGRADE_SAVING_VILLAGE_BONUS = 30;
export const UPGRADE_SAVING_VILLAGE_STAY_PUT_BONUS = 5;
export const TERRAIN_FOREST_PENALTY = -5;
export const TERRAIN_MOUNTAIN_BONUS = 10;
export const TERRAIN_PLAINS_NEUTRAL_BONUS = 40;
export const TERRAIN_PLAINS_OWNED_BONUS = 20;

// Upgrades
export const UPGRADE_GOLD_MINE_BONUS = 8.0; // Income is Primary Goal
export const UPGRADE_LAGGING_INCOME_BONUS = 5.0; 
export const UPGRADE_VILLAGE_BONUS = 6.0; // High priority for base expansion
export const UPGRADE_VILLAGE_LAGGING_INCOME_BONUS = 4.0;
export const UPGRADE_FORTRESS_BONUS = 0.5; // Defense is Secondary
export const UPGRADE_CASTLE_BONUS = 0.8;
export const STRATEGIC_FORTIFICATION_BONUS = 4.0;
export const DEFENSIVE_SUPPORT_VILLAGE_BONUS = 6.0;
export const GOLD_MINE_FRONTLINE_DISTANCE = 2;
export const GOLD_MINE_FRONTLINE_PENALTY = 1.0; // Be slightly braver with mines if income is critical
export const GOLD_MINE_BACKLINE_DISTANCE = 4;
export const GOLD_MINE_BACKLINE_BONUS = 3.0;
export const GOLD_MINE_BUFFER = 50;
export const FORTRESS_FRONTLINE_DISTANCE = 3;
export const FORTRESS_FRONTLINE_BONUS = 1.2;
export const FORTRESS_BACKLINE_BONUS = 0.4;
export const CASTLE_BUFFER = 100; // Lower buffers to keep spending on upgrades
export const FORTRESS_BUFFER = 50;
export const VILLAGE_BASE_SCORE = 15.0; // Massive push to increase income every turn
export const VILLAGE_ISOLATION_BONUS = 8.0;
export const VILLAGE_CLUSTERING_PENALTY = 0.05; // Almost ignore clustering if we have a spot
export const VILLAGE_CLUSTERING_SETTLEMENT_THRESHOLD_HIGH = 15;
export const VILLAGE_CLUSTERING_SETTLEMENT_THRESHOLD_MED = 10;
export const VILLAGE_CLUSTERING_PENALTY_MED_MULT = 0.1;
export const VILLAGE_MOUNTAIN_RESOURCE_BONUS = 0.5;
export const VILLAGE_FOREST_RESOURCE_BONUS = 0.15;
export const VILLAGE_WATER_RESOURCE_PENALTY = 0.05;
export const VILLAGE_MAP_EDGE_PENALTY = 0.1;
export const VILLAGE_MIN_SCORE_THRESHOLD = -5.0; // Allow building almost anywhere

// Threat Analysis & Influence
export const INFLUENCE_POWER_EXPONENT = 1.2;
export const INFLUENCE_DECAY_EXPONENT = 1.5;
export const SETTLEMENT_INFLUENCE_MULT = 5;
export const LAGGING_THRESHOLD = 0.85;
export const DOMINATING_THRESHOLD = 1.15;
export const HVT_CATAPULT_MULT = 2;
export const HVT_DISTANCE_FACTOR = 20;
export const HVT_SCORE_MULT = 10;
export const SAVING_VILLAGE_BASE_SCORE = 0.2;
export const SAVING_VILLAGE_ISOLATION_BONUS = 0.6;
export const SAVING_VILLAGE_CLUSTERING_PENALTY = 0.2;
export const SAVING_VILLAGE_MOUNTAIN_BONUS = 0.3;
export const SAVING_VILLAGE_FOREST_BONUS = 0.1;
export const SAVING_VILLAGE_WATER_PENALTY = 0.05;
export const SAVING_VILLAGE_MAP_EDGE_PENALTY = 0.1;
